# Create an environment.yml file with the desired packages and versions
name: mmr-py3-12
dependencies:
  - python=3.12
  - altair=5.2
  - matplotlib=3.8.2
  - notebook=7.0
  - pandas=2.2
  - pipreqs=0.4
  - seaborn=0.12
  - streamlit=1.31

# Create the conda environment with the environment.yml file
# conda env create -n mmr-py3-12 -f environment.yml

# Update the conda environment with the environment.yml file
# conda env update -n mmr-py3-12 -f environment.yml